// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/proto/v1/ipcheck.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InBlocklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *InBlocklistRequest) Reset() {
	*x = InBlocklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_ipcheck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InBlocklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InBlocklistRequest) ProtoMessage() {}

func (x *InBlocklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ipcheck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InBlocklistRequest.ProtoReflect.Descriptor instead.
func (*InBlocklistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ipcheck_proto_rawDescGZIP(), []int{0}
}

func (x *InBlocklistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type InBlocklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip          string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	InBlocklist bool   `protobuf:"varint,2,opt,name=in_blocklist,json=inBlocklist,proto3" json:"in_blocklist,omitempty"`
}

func (x *InBlocklistResponse) Reset() {
	*x = InBlocklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_ipcheck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InBlocklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InBlocklistResponse) ProtoMessage() {}

func (x *InBlocklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ipcheck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InBlocklistResponse.ProtoReflect.Descriptor instead.
func (*InBlocklistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ipcheck_proto_rawDescGZIP(), []int{1}
}

func (x *InBlocklistResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InBlocklistResponse) GetInBlocklist() bool {
	if x != nil {
		return x.InBlocklist
	}
	return false
}

type InitBlocklistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitBlocklistsRequest) Reset() {
	*x = InitBlocklistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_ipcheck_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBlocklistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBlocklistsRequest) ProtoMessage() {}

func (x *InitBlocklistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ipcheck_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBlocklistsRequest.ProtoReflect.Descriptor instead.
func (*InitBlocklistsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ipcheck_proto_rawDescGZIP(), []int{2}
}

type InitBlocklistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitBlocklistsResponse) Reset() {
	*x = InitBlocklistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_ipcheck_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBlocklistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBlocklistsResponse) ProtoMessage() {}

func (x *InitBlocklistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ipcheck_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBlocklistsResponse.ProtoReflect.Descriptor instead.
func (*InitBlocklistsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ipcheck_proto_rawDescGZIP(), []int{3}
}

var File_api_proto_v1_ipcheck_proto protoreflect.FileDescriptor

var file_api_proto_v1_ipcheck_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x69,
	0x70, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x24, 0x0a, 0x12, 0x49, 0x6e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x22, 0x48, 0x0a, 0x13, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x49, 0x6e,
	0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbe, 0x01,
	0x0a, 0x07, 0x49, 0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x54, 0x0a, 0x0b, 0x49, 0x6e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5d, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x73, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f,
	0x5a, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_ipcheck_proto_rawDescOnce sync.Once
	file_api_proto_v1_ipcheck_proto_rawDescData = file_api_proto_v1_ipcheck_proto_rawDesc
)

func file_api_proto_v1_ipcheck_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ipcheck_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ipcheck_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_ipcheck_proto_rawDescData)
	})
	return file_api_proto_v1_ipcheck_proto_rawDescData
}

var file_api_proto_v1_ipcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_ipcheck_proto_goTypes = []interface{}{
	(*InBlocklistRequest)(nil),     // 0: api.proto.v1.InBlocklistRequest
	(*InBlocklistResponse)(nil),    // 1: api.proto.v1.InBlocklistResponse
	(*InitBlocklistsRequest)(nil),  // 2: api.proto.v1.InitBlocklistsRequest
	(*InitBlocklistsResponse)(nil), // 3: api.proto.v1.InitBlocklistsResponse
}
var file_api_proto_v1_ipcheck_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.IpCheck.InBlocklist:input_type -> api.proto.v1.InBlocklistRequest
	2, // 1: api.proto.v1.IpCheck.InitBlocklists:input_type -> api.proto.v1.InitBlocklistsRequest
	1, // 2: api.proto.v1.IpCheck.InBlocklist:output_type -> api.proto.v1.InBlocklistResponse
	3, // 3: api.proto.v1.IpCheck.InitBlocklists:output_type -> api.proto.v1.InitBlocklistsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ipcheck_proto_init() }
func file_api_proto_v1_ipcheck_proto_init() {
	if File_api_proto_v1_ipcheck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_ipcheck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InBlocklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_ipcheck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InBlocklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_ipcheck_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBlocklistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_ipcheck_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBlocklistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_ipcheck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ipcheck_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ipcheck_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_ipcheck_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ipcheck_proto = out.File
	file_api_proto_v1_ipcheck_proto_rawDesc = nil
	file_api_proto_v1_ipcheck_proto_goTypes = nil
	file_api_proto_v1_ipcheck_proto_depIdxs = nil
}
