name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - run: gofmt -l

  vet:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - run: go vet
  
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - run: go test
